export enum CallRunStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  NO_ANSWER = 'NO_ANSWER',
  BUSY = 'BUSY',
  CANCELLED = 'CANCELLED',
  SKIPPED = 'SKIPPED',
}
export enum CallStatus {
  REGISTERED = 'REGISTERED',
  NOT_CONNECTED = 'NOT_CONNECTED',
  ONGOING = 'ONGOING',
  ENDED = 'ENDED',
  ERROR = 'ERROR',
}
